/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HighScore = IDL.Record({
  'moves' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, HighScore))],
      ['query'],
    ),
  'getMyHighScore' : IDL.Func([], [IDL.Opt(HighScore)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'initializeAuth' : IDL.Func([], [], []),
  'isCurrentUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveHighScore' : IDL.Func([IDL.Nat], [], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HighScore = IDL.Record({ 'moves' : IDL.Nat, 'timestamp' : IDL.Int });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, HighScore))],
        ['query'],
      ),
    'getMyHighScore' : IDL.Func([], [IDL.Opt(HighScore)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'initializeAuth' : IDL.Func([], [], []),
    'isCurrentUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveHighScore' : IDL.Func([IDL.Nat], [], []),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };